MajicMix:
  base: "C:/Users/Administrator/Downloads/stable-diffusion-v1-5"
  path: "C:/workspaces/stable-diffusion-webui/models/Stable-diffusion/majicmixRealistic_v7.safetensors"
  motion_module:
    - "outputs/model3/mm.path"
   
  seed:           [4216575493]
  steps:          50
  guidance_scale: 7.5

  prompt:
    - "1girl,front,off-white and round neck sweater dress,full body,orange background"
   
  n_prompt:
    - "ng_deepnegative_v1_75t, badhandv4, worst quality, low quality, normal quality, lowres, bad anatomy, bad hands, watermark, moles"
   